add __eq__ to Device
helmholtz-analytics/heat pull request #1063
Opened 2022-12-20 16:27 UTC by mtar

## Description

This PR overloads the '==' operator such that devices can be compared.

Issue/s resolved: #1062 

## Changes proposed:
- add __eq__ operator

## Type of change

- New feature

## Memory requirements

n/a

## Performance

n/a

## Due Diligence
- [x] All split configurations tested
- [x] Multiple dtypes tested in relevant functions
- [x] Documentation updated (if needed)
- [x] Title of PR is suitable for corresponding CHANGELOG entry

#### Does this change modify the behaviour of other functions? If so, which?
no

2023-01-19 09:03 UTC, Markus-Goetz requested changes

2023-01-19 09:03 UTC, Markus-Goetz commented on heat/core/devices.py
> +                if (self.device_type == other.device_type and self.device_id == other.device_id)
You can shorten this to a return of the condition, i.e. return self.device_type == other...

2023-01-19 09:03 UTC, Markus-Goetz commented on heat/core/devices.py
> +                if (self.device_type == other.type and self.device_id == other.index)
Can equally be shortened, see above

2023-01-23 08:49 UTC, ClaudiaComito approved these changes
Great, thanks @mtar!

2023-01-23 13:57 UTC, merged