Work/hermitian
helmholtz-analytics/heat pull request #1086
Opened 2023-02-02 15:54 UTC by swaptr

## Description
Added `hermitian()` to generate random hermitian matrices of size `n`.

Issue/s resolved: #1073 

## Changes proposed:
- Add `hermitian()` to `utils.data.matrixgallery`.

## Type of change
- New feature (non-breaking change which adds functionality)

## Memory requirements
- NA

## Performance
- NA

## Due Diligence
- [ ] All split configurations tested
- [ ] Multiple dtypes tested in relevant functions
- [ ] Documentation updated (if needed)
- [ ] Title of PR is suitable for corresponding CHANGELOG entry

#### Does this change modify the behaviour of other functions? If so, which?
no

2023-02-02 15:56 UTC, swaptr commented
@ClaudiaComito I could'nt figure out the split logic for this. Can you please review the PR?

2023-08-17 18:47 UTC, ClaudiaComito requested changes
Thanks again @swaptr and apologies for the delay. I suggest to use `ht.random.randn` instead of `arange`, and that also allows specifying a split axis.

2023-08-17 18:47 UTC, ClaudiaComito commented on heat/utils/data/matrixgallery.py
> +    dtype: Type[datatype] = core.float32,
```suggestion
    dtype: Type[datatype] = core.complex64,
```

2023-08-17 18:47 UTC, ClaudiaComito commented on heat/utils/data/matrixgallery.py
> +    conjugate matrix.
```suggestion
    Generates a Hermitian matrix of arbitrary size. A Hermitian matrix is a  complex square matrix that is equal to its conjugate transpose.
```

2023-08-17 18:47 UTC, ClaudiaComito commented on heat/utils/data/matrixgallery.py
> +
```suggestion
    dtype: Type[datatype], optional
        The desired data-type for the array, defaults to ht.complex64.

```

2023-08-17 18:47 UTC, ClaudiaComito commented on heat/utils/data/matrixgallery.py
> +
```suggestion
    return matrix @ core.conj(matrix).T
```

2023-08-18 12:41 UTC, ClaudiaComito requested changes

2023-08-18 12:41 UTC, ClaudiaComito commented on heat/utils/data/matrixgallery.py
> +    real_dtype = types.float32 if dtype is types.complex64 else types.float64
```suggestion
    real_dtype = core.float32 if dtype is core.complex64 else core.float64
```

2023-08-19 05:58 UTC, merged