Validates number of dimensions in input
helmholtz-analytics/heat pull request #1098
Opened 2023-02-08 14:22 UTC by Ishaan-Chandak

# Description

ht.sparse.sparse_csr_matrix should accept only 2-D input. But it accepts (and crashes) when the input is not 2 dimensional.

The input must be properly validated to ensure only 2-D input is accepted. Or else an error with the message "The number of dimensions must be 2, found ndim" must be raised.

# Changes proposed

Using tensor.ndim to find the dimension of the tensor and then using if-else statements to check the dimension of the input and raise the exception.

2023-02-08 15:34 UTC, Mystic-Slice commented
Try to provide some supporting unit tests for this change once you fix this. 
And of course, don't hesitate to ask here if you have any doubts.

2023-02-09 10:41 UTC, Ishaan-Chandak commented
Hi, @Mystic-Slice I made the necessary changes please review the PR, I also ran all the unittests as mentioned in the documentation provided.
Thank you

2023-02-09 10:44 UTC, Ishaan-Chandak commented
I am extremely sorry for this commit I messed up the code at a point I ll make the changes as soon as possible 
Sorry @Mystic-Slice

2023-02-09 10:59 UTC, Mystic-Slice requested changes

2023-02-09 10:59 UTC, Mystic-Slice commented on heat/sparse/factories.py
> +        raise Exception("The number of dimensions must be 2, found " + str(obj.ndim))
raise a `ValueError` instead of an `Exception`.

2023-02-09 11:02 UTC, Mystic-Slice commented
@Ishaan-Chandak New tests need to be added to the existing unit-tests to ensure the check for dimensionality works properly.
You can create the new tests in [heat/core/tests/test_factories.py](https://github.com/helmholtz-analytics/heat/blob/main/heat/core/tests/test_factories.py)

2023-02-09 11:10 UTC, Ishaan-Chandak commented
I ll be adding the tests soon @Mystic-Slice

2023-02-09 14:04 UTC, Ishaan-Chandak commented
Hi @Mystic-Slice 
`def test_dimensions(self):
        # for a two dimension tensor no error is raised
        
        # more than two dimension tensors with sparse_csr layout 
        a = torch.tensor([[[0, 1]]], dtype=torch.float64).to_sparse_csr()
        self.assertRaises(ValueError, ht.sparse.sparse_csr_matrix, a)

        # for one dimension 
        self.assertRaises(ValueError, ht.sparse.sparse_csr_matrix, torch.tensor([0, 1]))
        self.assertRaises(ValueError, ht.sparse.sparse_csr_matrix, torch.tensor([1, 0, 3]))
        self.assertRaises(ValueError, ht.sparse.sparse_csr_matrix, torch.tensor([ ]))
        self.assertRaises(ValueError, ht.sparse.sparse_csr_matrix, torch.tensor([1, 0, 3, 4]))

        # for more than one dimension
        self.assertRaises(ValueError, ht.sparse.sparse_csr_matrix, torch.tensor([[[1, 0, 3]]]))
`
Are these many unit-tests enough ?

2023-02-09 16:00 UTC, Ishaan-Chandak commented
@Mystic-Slice Is test for 2-D input necessary because when the input is 2-D the programs keeps on running without any interruptions.
So according to me it will be better to have two inputs one for greater than 2 and one for less than 2

2023-02-09 16:05 UTC, Mystic-Slice commented
Yes, I meant exactly that by `> 2-D` (greater than 2-D). :)

2023-02-10 04:09 UTC, Ishaan-Chandak commented
Hi @Mystic-Slice I have added the tests and made the changes as you told me to do please review the commit.

2023-02-12 04:17 UTC, Ishaan-Chandak commented
Hi @Mystic-Slice Can you please review this and tell me if any changes are needed.
Thank you

2023-02-13 14:39 UTC, Mystic-Slice approved these changes
Looks good to me

2023-02-13 14:53 UTC, Mystic-Slice commented
@ClaudiaComito This PR is good to be merged. The pre-commit ci failure is not related to this PR.

And @Ishaan-Chandak Nice work!

2023-02-15 04:53 UTC, ClaudiaComito approved these changes
Wonderful, thanks a lot @Ishaan-Chandak and @Mystic-Slice !

2023-03-06 03:43 UTC, ClaudiaComito commented
This PR needs CI. Waiting on developments in #1114

2023-03-07 12:52 UTC, Mystic-Slice commented
@Ishaan-Chandak CI is Continuous Integration. It is the tests that run before the PR is allowed to be merged. You might have noticed that some tests do not run in your PR. That is because CI, as of now, does not work on external contributor forks. And the work to enable CI for external forks is going on in #1114. Your work here is complete. We will merge the PR once it is ready. Thanks for the fix. We will take care of the rest.

**tldr**, You do not need to do anything.

2023-03-07 17:49 UTC, ClaudiaComito commented
> Hi @ClaudiaComito I am unable to understand what should I do now ? And can you please explain what exactly is CI

@Ishaan-Chandak oh I'm so sorry, that was more of an internal communication 😬 apologies. @Mystic-Slice thanks for explaining. Once we can run the tests, we'll know if more needs to be done. Nothing you can do about this @Ishaan-Chandak , thanks again for your time!

2023-03-09 07:26 UTC, Ishaan-Chandak commented
Hi @Mystic-Slice @ClaudiaComito I received a mail regarding some tests failing due to older version of heat so should i do something to rectify them ?

2023-03-20 07:57 UTC, ClaudiaComito commented
> Hi @Mystic-Slice @ClaudiaComito I received a mail regarding some tests failing due to older version of heat so should i do something to rectify them ?

@Ishaan-Chandak no that was still our old tests. We have merged the new ones now, I'm about to merge this PR. 👏🏼 Thanks @Ishaan-Chandak  @mtar and @Mystic-Slice for all the work!

2023-03-20 09:01 UTC, merged