Drop support for pytorch 3.17
helmholtz-analytics/heat pull request #1147
Opened 2023-04-28 09:15 UTC by mtar

## Description
This Pull Request tidies up some code targeting older versions of Python and PyTorch.

Issue/s resolved: #1145 

## Changes proposed:
- rise min dependency PyTorch to 1.8
- delete code targeting PyTorch <= 1.7
- delete code targeting Python <= 3.6

## Type of change
- Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Memory requirements
n/a

## Performance
n/a

## Due Diligence
- [x] All split configurations tested
- [x] Multiple dtypes tested in relevant functions
- [x] Documentation updated (if needed)
- [x] Title of PR is suitable for corresponding CHANGELOG entry

#### Does this change modify the behaviour of other functions? If so, which?
no

2023-05-19 13:22 UTC, ClaudiaComito submitted a review, later dismissed

2023-05-22 03:35 UTC, ClaudiaComito requested changes
It seems older pytorch versions don't support Python 3.10.

Does it make sense to add torch 2 right away, since we're close to merging #1155 ?

2023-05-22 17:09 UTC, ClaudiaComito approved these changes

2023-05-23 07:24 UTC, ClaudiaComito approved these changes

2023-05-23 07:42 UTC, ClaudiaComito commented
@mtar does this PR also solve #1146 ?

2023-05-23 07:52 UTC, mtar commented
> @mtar does this PR also solve #1146 ?

For the next release? Yes

2023-05-23 08:34 UTC, merged