Implementation of module `preprocessing`
helmholtz-analytics/heat pull request #1172
Opened 2023-06-26 13:19 UTC by mrfh92

In this PR we want to implement a preprocessing module for heat that has roughly the same capabilities as [the one of scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html). 

A good idea to start is: 

* StandardScaler
* MaxAbsScaler
* MinMaxScaler
...

2023-06-26 15:50 UTC, mrfh92 commented
current problem in `StandardScaler`: sth is wrong with the variance computation...

2023-07-12 08:18 UTC, mrfh92 commented
@krajsek From your experience in the neuroscience community, is there another preprocessing tool (e.g., from the list of scikit-learn) we should definitively add?

2023-07-12 15:35 UTC, krajsek commented
@mrfh92 No, not at that level. There are a large number of preprocessing steps used in neuroimaging pipelines but they are more own image processing algorithms like motion correction, slice timing corrction or registration. But on this level, simple normalization etc. I cannot think about any neuroscience specific preprocesssing steps. Apart from that I think OneHotEncoder is quite usefull.

2023-07-27 14:00 UTC, mrfh92 commented
to be discussed: 
* which additional preprocessing routines (e.g., from those available in `scikit-learn`) could/should be added?
* which of the routines from this module should be part of continuous benchmarking

2023-08-17 12:27 UTC, mrfh92 commented
extensive citation of scikit-learn should be added in the docs

2023-08-18 15:52 UTC, mrfh92 commented
@mtar I have addressed most issues you mentioned in the last PR talk 
only type hints for returned `self` seem to be a bit tricky, because `from typing import Self` produces an error for me...

2023-08-25 09:34 UTC, mtar commented
@mrfh92 the _Self_ type was introduced in Python 3.11, on older versions you can import it from the _typing_extensions_ module

2023-08-25 10:29 UTC, mrfh92 commented
@mtar thanks for the hint ... i have added the respective changes

2023-09-04 04:00 UTC, ClaudiaComito requested changes
Thank you so much @mrfh92 , this is very timely.  I have a few comments.

2023-09-04 08:50 UTC, mrfh92 commented on heat/core/io.py
> +                    raise ValueError("load_fraction can only be used if split is not None.")
I have chosen 2.

2023-09-04 09:23 UTC, mrfh92 commented on heat/preprocessing/preprocessing.py
> +        else:
if #1184 has been done, this will make a difference i guess (?)

2023-09-04 09:24 UTC, mrfh92 commented on heat/preprocessing/preprocessing.py
> +        else:
sry misunderstood this ... you're right

2023-09-04 09:34 UTC, mrfh92 commented on heat/preprocessing/preprocessing.py
> +            return Y
I have added `.copy()` here. Full functionality of in-place transformations can be assessed only if #1184 has been implemented.

2023-09-04 09:54 UTC, mrfh92 commented
I have done the requested changes

2023-09-07 14:55 UTC, ClaudiaComito approved these changes
Thanks for the changes @mrfh92 !

2023-09-07 15:35 UTC, merged