added `ht.broadcast_shapes` method and unit test
helmholtz-analytics/heat pull request #1215
Opened 2023-09-05 18:40 UTC by samadpls

## Due Diligence

- General:
    - [X]  **base branch** must be `main` for new features, latest release branch (e.g. `release/1.3.x`) for bug fixes
    - [X]  **title** of the PR is suitable to appear in the [Release Notes](https://github.com/helmholtz-analytics/heat/releases/latest)
- Implementation:
    - [X] unit tests: all split configurations tested
    - [X] unit tests: multiple dtypes tested
    - [X] documentation updated where needed

## Description
This PR addresses issue #904  by implementing `ht.broadcast_shapes`to align with numpy and torch counterparts in terms of naming, calling, and handling multiple shapes.

Issue/s resolved: #904 

## Changes proposed:
- Added ht.broadcast_shapes with the desired behavior.

## Type of change

New feature (non-breaking change which adds functionality)
## Memory requirements
Memory requirements for this change have not been profiled at this time.

## Performance
Performance metrics for this change have not been measured at this time.

#### Does this change modify the behaviour of other functions? If so, which?
no

2023-09-06 07:24 UTC, samadpls commented
Hey @ClaudiaComito, could you please review this whenever it's convenient for you?

2023-09-07 13:53 UTC, ClaudiaComito requested changes
Wonderful @samadpls, just a small change needed.

2023-09-07 13:53 UTC, ClaudiaComito commented on heat/core/stride_tricks.py
> +        return tuple(resulting_shape[::-1])
actually we stopped supporting torch<1.8 so this shouldn't be necessary

2023-09-07 14:57 UTC, ClaudiaComito approved these changes
👏🏼 @samadpls thanks!

2023-09-07 15:36 UTC, ClaudiaComito approved these changes

2023-09-07 16:44 UTC, merged