Remove calls to deprecated `Tensor.storage()` when using newer PyTorch versions
helmholtz-analytics/heat pull request #1230
Opened 2023-10-06 13:18 UTC by mrfh92

Intended to resolve issue #1229

2023-10-06 13:22 UTC, mrfh92 commented
merged `main` (although this is labeled as "bug"-PR) because it is actually not a bug-fix but rather a reaction to some future development in PyTorch and therefore this PR can wait til next release to become "proper" part of Heat

2023-10-06 14:46 UTC, mrfh92 commented
The first idea for a workaround mentioned above that resulted in errors only in `test_stride_and_strides` does not seem to work for certain earlier PyTorch versions. I have tested with torch==2.0.0 on my worksation (result above), but torch==1.8.1 (also on my workstation) and torch==1.12.0 (on HDFML) which resulted in multiple errors over many unittests.  When I use torch==2.0.0 on HDFML, I only get errors in `test_stride_and_strides` again...

2023-10-06 15:40 UTC, mrfh92 commented
Still a problem: 
```
/p/project/haf/users/hoppe6/heat/heat/optim/dp_optimizer.py:23: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  tens_a = torch.HalfTensor().set_(torch.HalfStorage.from_buffer(buffer_a, "native"))
```

2023-10-09 14:28 UTC, mrfh92 commented
Current workaround works on HDFML with torch==1.12 and torch==2.0.0 execpt for the following problems: 

```
/p/project/haf/users/hoppe6/heat/heat/optim/dp_optimizer.py:23: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  tens_a = torch.HalfTensor().set_(torch.HalfStorage.from_buffer(buffer_a, "native"))
```
and similar for lines 24, 33, and 34 of the same file.

2023-10-09 14:30 UTC, mrfh92 commented
**Comment on decreased codecov:** 
This is mainly due to the fact that I now skipp all DASO-related tests as long as the hardware is inappropriate (i.e., no GPUs or less than 2 nodes), which is the case for our CI-runners. Hence, DASO is not covered anymore.

2023-10-09 15:12 UTC, mrfh92 commented
Workaround for DASO has successfully been tested on HDFML (2 nodes, 4 GPUs each) with PyTorch==1.12.0 and PyTorch==2.0.0.

2023-10-13 09:51 UTC, ClaudiaComito requested changes
Great @mrfh92 thanks a lot for fixing this. I only have one potential change in the `version.py` file since we are merging into `main`.

Thanks a lot!

2023-10-13 09:51 UTC, ClaudiaComito commented on heat/core/version.py
> +extension: str = None
we're merging into `main`, correct?

2023-10-13 10:24 UTC, ClaudiaComito approved these changes
Awesome!

2023-10-13 10:45 UTC, merged