Batched matrix multiplication.
helmholtz-analytics/heat pull request #1261
Opened 2023-11-08 13:36 UTC by FOsterfeld

split dimension is a batch dimension

## Due Diligence

- General:
    - [ ]  **base branch** must be `main` for new features, latest release branch (e.g. `release/1.3.x`) for bug fixes
    - [ ]  **title** of the PR is suitable to appear in the [Release Notes](https://github.com/helmholtz-analytics/heat/releases/latest)
- Implementation:
    - [ ] unit tests: all split configurations tested
    - [ ] unit tests: multiple dtypes tested
    - [ ] documentation updated where needed

## Description

Issue/s resolved: #

## Changes proposed:

-
-
-
-

## Type of change

## Memory requirements

## Performance

#### Does this change modify the behaviour of other functions? If so, which?
yes / no

2023-11-10 16:33 UTC, mrfh92 commented on heat/core/linalg/basics.py
> +    batched = batch_dim > 2
> 0 ?

2023-11-13 07:59 UTC, mrfh92 commented
Sieht gut aus soweit :+1:

Vorschläge für die weitere Arbeit: 
* Wenn du oben neben "codecov" (rotes X) auf Details und dann auf "View this Pull Request on Codecov" gehst, kannst du sehen, welche Zeilen deiner Änderungen nicht getestet werden bisher. Entsprechende Tests kannst du in `heat/core/linalg/tests/test_basics.py` unterbringen. 
Mit diesem Fall wäre dann gebatchte Matrizenmultiplikation für den Fall abgedeckt, dass die LA-Dimensionen nicht gesplitted sind. Dies entspricht quasi dem Hinzufügen von Batchdimensionen zum Fall "2x`split=None`" im ursprünglichen Code. 
* Als nächstes könnten wir den Fall angehen, dass zu den anderen 8 (?) bestehenden Fällen Batch-dimensionen hinzugefügt werden; nun wäre allerdings die Batchdimension nicht gesplitted und dafür evtl. die LA-Dimension. Mit etwas Glück lässt sich das recht einfach aus dem bestehenden Code erzeugen, da ja PyTorch bereits gut mit Batches arbeiten kann. 
* Den Fall, dass einmal eine LA-Dimension gesplitted ist und einmal eine Batchdimension gesplitted ist, würde ich ausschließen und eine enstprechende Fehlermeldung ausgeben.

2023-11-21 10:20 UTC, FOsterfeld commented on heat/core/linalg/basics.py
> +    batched = batch_dim > 2
Thanks, you're right, it should be 0.

2024-06-20 23:19 UTC, FOsterfeld commented
Regarding the possible memory issue of #360, I benchmarked the maximal memory usage of matmul for two n x n matrices in the possible split cases.

![plot_matmul-heat_2](https://github.com/helmholtz-analytics/heat/assets/146953335/6ecd1574-70c5-467f-9cf6-db163bedeaea)

2024-06-21 15:45 UTC, FOsterfeld commented
The same plot with log scaling in the y-axis: 

![plot_matmul-heat_2](https://github.com/helmholtz-analytics/heat/assets/146953335/8783a493-1c23-41f0-ae69-1f3942055bfb)

2024-06-25 06:00 UTC, mrfh92 commented
@FOsterfeld thx :+1:
@ClaudiaComito I think we can use this diagram as basis for further refactoring efforts of matmal in the future

2024-07-02 08:44 UTC, mrfh92 commented
@FOsterfeld For now, I would suggest to add a hint to the docs that in terms of memory consumption the combinations 01, 00, 11 (and 0None, None1) seem to perform quite good, whereas the split combinations 10, None0 and 1None should be avoided due to comparably high memory consumption.

2024-07-11 06:34 UTC, mtar requested changes
I realised that the additions are a copy and paste of the existing code for the most part. Can you incorporate the changes or reuse it instead?

2024-07-12 17:45 UTC, FOsterfeld commented
@mrfh92 Here is the plot of the runtimes from the last benchmark:
![plot_matmul-heat-runtime_2](https://github.com/user-attachments/assets/9b84a55b-124b-4c37-93fc-aadc427a996c)`

2024-07-13 21:54 UTC, FOsterfeld commented
@mrfh92 Here are plots of the runtime and memory usage of the the bad split combinations and the case that we do resplit instead. Specifically, we resplit 1-0 to 0-0, 1-None to 1-1 and None-0 to 0-0.

![plot_matmul-resplit-runtime_2](https://github.com/user-attachments/assets/fee2ea09-8379-4b79-a31c-3a93801487f6)

![plot_matmul-resplit-memory_2](https://github.com/user-attachments/assets/68196b4e-66d8-4502-9b66-f9f107041bd7)

2024-07-15 07:15 UTC, mrfh92 commented
@FOsterfeld thx for the plots :+1:

2024-07-17 14:01 UTC, FOsterfeld commented on heat/core/linalg/basics.py
> +    - If ``a`` is a split vector then the returned vector will be of shape (:math:`1xQ`) and will be split in the 1st dimension. If ``b`` is a vector and either ``a`` or ``b`` is split, then the retu
@mtar How can I get this preview? On read the docs I only found the docs for the releases.

2024-07-18 06:05 UTC, mtar commented on heat/core/linalg/basics.py
> +    - If ``a`` is a split vector then the returned vector will be of shape (:math:`1xQ`) and will be split in the 1st dimension. If ``b`` is a vector and either ``a`` or ``b`` is split, then the retu
The documentation describes in the part [Writing Heat Documentation](https://heat.readthedocs.io/en/stable/documentation_howto.html) how to build it locally.

2024-08-17 12:21 UTC, FOsterfeld commented
> I realised that the additions are a copy and paste of the existing code for the most part. Can you incorporate the changes or reuse it instead?

Now there should be no more code duplications for the batched/unbatched cases.

2024-08-20 13:53 UTC, mrfh92 commented
@FOsterfeld Something seems to have changed that lets the tests in QR fail. Can you reproduce this error on the workstation?

2024-09-04 10:06 UTC, JuanPedroGHM approved these changes
:+1:

2024-09-04 14:55 UTC, mrfh92 commented
@mtar have your suggestions been addressed by the changes?

2024-09-06 06:00 UTC, mtar approved these changes

2024-09-06 06:12 UTC, JuanPedroGHM commented
### Benchmarks results - Sponsored by [perun](https://github.com/Helmholtz-AI-Energy/perun)

| function                                |   mpi_ranks | device   | metric   |      value |   ref_value |         std |   % change | type            | alert   |   lower_quantile |   upper_quantile |
|-----------------------------------------|-------------|----------|----------|------------|-------------|-------------|------------|-----------------|---------|------------------|------------------|
| matmul_split_1                          |           4 | CPU      | RUNTIME  | 0.122906   |  0.109381   | 0.0313848   |   12.3656  | jump-detection  | True    |     nan          |     nan          |
| concatenate                             |           4 | CPU      | RUNTIME  | 0.167615   |  0.196439   | 0.0260386   |  -14.6728  | jump-detection  | True    |     nan          |     nan          |
| apply_inplace_normalizer                |           4 | CPU      | RUNTIME  | 0.00100724 |  0.00947982 | 8.56803e-05 |  -89.375   | jump-detection  | True    |     nan          |     nan          |
| matmul_split_0                          |           4 | GPU      | RUNTIME  | 0.0483279  |  0.0545347  | 0.0310459   |  -11.3814  | jump-detection  | True    |     nan          |     nan          |
| matmul_split_1                          |           4 | GPU      | RUNTIME  | 0.0367425  |  0.0272262  | 0.0292762   |   34.9526  | jump-detection  | True    |     nan          |     nan          |
| qr_split_1                              |           4 | CPU      | RUNTIME  | 0.179386   |  0.451767   | 0.00646491  |  -60.2924  | trend-deviation | True    |       0.179536   |       0.796189   |
| kmeans                                  |           4 | CPU      | RUNTIME  | 0.309642   |  0.909418   | 0.00239133  |  -65.9517  | trend-deviation | True    |       0.312577   |       1.79242    |
| reshape                                 |           4 | CPU      | RUNTIME  | 0.155737   |  0.365847   | 0.00110721  |  -57.431   | trend-deviation | True    |       0.156546   |       0.731662   |
| lanczos                                 |           4 | GPU      | RUNTIME  | 0.600791   |  0.586755   | 0.00316215  |    2.39205 | trend-deviation | True    |       0.579288   |       0.597313   |
| kmeans                                  |           4 | GPU      | RUNTIME  | 0.657029   |  0.632586   | 0.004188    |    3.86392 | trend-deviation | True    |       0.617689   |       0.64691    |
| kmedians                                |           4 | GPU      | RUNTIME  | 1.11586    |  1.01658    | 0.0125118   |    9.76642 | trend-deviation | True    |       0.994589   |       1.04602    |
| kmedoids                                |           4 | GPU      | RUNTIME  | 1.2525     |  1.14701    | 0.00847031  |    9.19655 | trend-deviation | True    |       1.12248    |       1.18111    |
| apply_inplace_robust_scaler_and_inverse |           4 | GPU      | RUNTIME  | 5.99905    |  5.60869    | 0.0446267   |    6.95995 | trend-deviation | True    |       5.47179    |       5.75939    |
| apply_inplace_normalizer                |           4 | GPU      | RUNTIME  | 0.00179942 |  0.00169872 | 4.94232e-05 |    5.92757 | trend-deviation | True    |       0.00166147 |       0.00175474 |

[Grafana Dashboard](http://57bc8d92-72f2-4869-accd-435ec06365cb.ka.bw-cloud-instance.org:3000/d/adjpqduq9r7k0a/heat-cb?orgId=1)
Last updated: 2024-09-06T06:12:05Z

2024-09-09 03:55 UTC, merged