Patch release guide
helmholtz-analytics/heat pull request #1280
Opened 2023-11-23 13:37 UTC by JuanPedroGHM

## Due Diligence

- General:
    - [ ]  **base branch** must be `main` for new features, latest release branch (e.g. `release/1.3.x`) for bug fixes
    - [ ]  **title** of the PR is suitable to appear in the [Release Notes](https://github.com/helmholtz-analytics/heat/releases/latest)
- Implementation:
    - [ ] unit tests: all split configurations tested
    - [ ] unit tests: multiple dtypes tested
    - [ ] documentation updated where needed

## Description

Updates RELEASE.md with step-by-step guide to releasing a patch version of heat to PyPI and to conda-forge. Steps for releasing mayor and minor versions to conda-forge were added as well. 

Issue/s resolved: #

## Changes proposed:

- Documentation changes in RELEASE.md

## Type of change
- Documentation update

#### Does this change modify the behaviour of other functions? If so, which?
no

2023-11-27 04:49 UTC, ClaudiaComito requested changes
Thanks a lot @JuanPedroGHM for all the help last week and for updating the instructions. I've suggested a few changes in the review.

2023-11-27 04:49 UTC, ClaudiaComito commented on RELEASE.md
> +10. Now we want to update `main` to the latest version, and we want the version on `main` to be `1.3.0-dev`.
```suggestion
10. Now we want to update `main` to the latest version, and we want the version on `main` to be `1.4.0-dev`.
```

2023-11-27 04:49 UTC, ClaudiaComito commented on RELEASE.md
> +1. Check that all intended branches have been merged to `main`. Branch off from main and create a new release branch:
```suggestion
1. Check that all intended branches have been merged to the release branch you want to upgrade, in this example `release/1.3.x`. Branch off from `release/1.3.x` and create a new branch:
```

2023-11-27 04:49 UTC, ClaudiaComito commented on RELEASE.md
> +
Save but do not publish?

2023-11-27 04:49 UTC, ClaudiaComito commented on RELEASE.md
> +  - Create a PR from `workflow/merge-latest-release-into-main`
```suggestion
  - Create a new branch from `release/1.3.x`, for example `merge-latest-release-into-main`
  - Merge `main` into `merge-latest-release-into-main`, resolve conflicts and push.
  - Create a PR from `merge-latest-release-into-main`, base branch must be `main`
```

2023-11-27 04:49 UTC, ClaudiaComito commented on RELEASE.md
> +  - Make sure the version number is corrent in main.
```suggestion
  - Make sure the version number in `merge-latest-release-into-main` is correct (i.e., it matches that in `main`).
```

2023-11-27 04:49 UTC, ClaudiaComito commented on RELEASE.md
> +  - Make sure the CHANGELOG.md is the same in both branches.
```suggestion
  - Make sure the CHANGELOG.md in `merge-latest-release-into-main` matches that in the latest release branch, in this example`release/1.3.x`.
```

2023-12-07 11:17 UTC, JuanPedroGHM commented on RELEASE.md
> +
:+1:

2023-12-11 08:55 UTC, ClaudiaComito submitted a review, later dismissed
Great, thanks a lot @JuanPedroGHM !

2023-12-22 11:33 UTC, ClaudiaComito approved these changes
Thanks a lot @JuanPedroGHM !

2024-01-08 09:31 UTC, ClaudiaComito approved these changes

2024-02-05 08:59 UTC, merged