Batch-parallel K-means and K-medians
helmholtz-analytics/heat pull request #1288
Opened 2023-11-30 16:14 UTC by mrfh92

## Due Diligence

- General:
    - [ ]  **base branch** must be `main` for new features, latest release branch (e.g. `release/1.3.x`) for bug fixes
    - [ ]  **title** of the PR is suitable to appear in the [Release Notes](https://github.com/helmholtz-analytics/heat/releases/latest)
- Implementation:
    - [ ] unit tests: all split configurations tested
    - [ ] unit tests: multiple dtypes tested
    - [ ] documentation updated where needed

## Description

Issue/s resolved: #

## Changes proposed:

-
-
-
-

## Type of change

## Memory requirements

## Performance

#### Does this change modify the behaviour of other functions? If so, which?
yes / no

2023-12-11 04:34 UTC, ClaudiaComito requested changes
@mrfh92 this is great. 

Would it be possible or advisable to make batch-parallel clustering available from within a general `ht.cluster.KMeans` call? I'm thinking something like:

```python
kmeans = ht.cluster.KMeans(n_clusters=k, parallel="batch")
```
where `parallel` can be "batch" or "standard".

2024-02-28 13:06 UTC, mrfh92 commented
@ClaudiaComito I think K-Means/Medians and Batch-parallel K-Means/Medians should be handled as separate functions since from an algorithmic point of view they are quite different. However, it's possible (and I have done so) to add batch-parallel K-Means/Medias as additional Initialization for classical K-Means/Medians

2024-04-11 08:10 UTC, ClaudiaComito requested changes
Looks great to me @mrfh92 , I only have a few edits to the documentation. Otherwise we can merge.

2024-04-11 08:10 UTC, ClaudiaComito commented on heat/cluster/batchparallelclustering.py
> +    This requires data to be given as DNDarray of shape (n_samples, n_features) with split=0 (i.e. split along the sample axis).
```suggestion
    The input must be a ``DNDarray`` of shape `(n_samples, n_features)`, with split=0 (i.e. split along the sample axis).
```

2024-04-11 08:10 UTC, ClaudiaComito commented on heat/cluster/batchparallelclustering.py
> +    The idea of the method is to perform the classical K-Means on each batch of data (i.e. on each process-local chunk of data) individually and in parallel.
```suggestion
    This method performs K-Means clustering on each batch (i.e. on each process-local chunk) of data individually and in parallel.
```

2024-04-11 09:20 UTC, mrfh92 commented
@ClaudiaComito I have committed all suggested changes.

2024-04-12 12:22 UTC, ClaudiaComito approved these changes
:clap: @mrfh92 !

2024-04-12 12:34 UTC, merged