Refactoring of QR
helmholtz-analytics/heat pull request #1329
Opened 2024-01-22 14:26 UTC by mrfh92

TBD

2024-01-22 15:02 UTC, mrfh92 commented
Suggested handling of the options: 

* batches of matrices allowed 
* mode{‘reduced’, ‘complete’, ‘r’, ‘raw’}, optional with default  "reduced"

2024-02-05 16:04 UTC, mrfh92 commented
@mtar fyi: your update of the PyTorch/ROCm-image on the AMD-runner allows us now to test QR on AMD, too :+1:

2024-02-06 11:55 UTC, mrfh92 commented
@ClaudiaComito @mtar hopefully, this resolves the previous problems with QR 
@JuanPedroGHM cb/report is still "Pending" although the benchmarks have been run successfully in gitlab and also report success has been finished ... is there some problem with this?

2024-02-06 14:04 UTC, JuanPedroGHM commented
> @ClaudiaComito @mtar hopefully, this resolves the previous problems with QR @JuanPedroGHM cb/report is still "Pending" although the benchmarks have been run successfully in gitlab and also report success has been finished ... is there some problem with this?

Fixed, the CB does not require the assignee tag to be set any more.

2024-02-06 15:16 UTC, mrfh92 commented
@JuanPedroGHM thx :+1:

2024-02-19 05:01 UTC, ClaudiaComito commented on heat/core/linalg/qr.py
> +                "A is split along the rows and the local chunks of data are rectangular with more rows than columns. \n Applying TS-QR in this situation is not reasonable w.r.t. runtime and memory co
This is going to be weird for the users. You can start with a global TS matrix and end up with non-TS local arrays if you use enough processes. We need to explain it better / introduce an earlier check, maybe make a helper function available that calculates the most reasonable split for  given matrix size and nr of processes? I'll think about it some more.

2024-02-19 05:04 UTC, ClaudiaComito commented on heat/core/linalg/qr.py
> +# old version with serial sends instead of broadcast...
dead code? (below too)

2024-02-27 14:52 UTC, mrfh92 commented on heat/core/linalg/qr.py
> +                req.Wait()
Replacing these two lines by `A.comm.Bcast(Q_buf,root=i)` yields `MPI_ERR_TRUNCATE`

2024-02-27 14:54 UTC, mrfh92 commented on heat/core/linalg/qr.py
> +        R = DNDarray(
I think that for consistency it would be better to keep the same allowed modes for all split-variants

2024-04-16 12:01 UTC, ClaudiaComito requested changes
Thanks for all the work, a few comments:

2024-04-17 10:36 UTC, mrfh92 commented on benchmarks/cb/linalg.py
> +    a_0 = ht.random.random((m, n), split=0)
as far as I understand, the function to be monitored is `def qr_split_1(a)`, so the generation of test data is already outside the monitored area

2024-04-17 10:40 UTC, mrfh92 commented on heat/core/linalg/qr.py
>      If ``calc_q==True``, function returns ``QR(Q=Q, R=R)``, else function returns ``QR(Q=None, R=R)``
Taken into account. Added notice on how to replace calc_q under "notes".

2024-04-17 10:43 UTC, mrfh92 commented on heat/core/linalg/qr.py
> +    For split=1, Q and R have split=1 as well. For split=0, Q has split=0 and R has split=None.
added

2024-04-17 10:48 UTC, mrfh92 commented on heat/core/linalg/qr.py
> +    Other than ``numpy.linalg.qr()`` we only support ``mode="reduced"`` or ``mode="r"`` for the moment, since "complete" may result in heavy memory usage.
have taken the reformulation into account. 

communication overhead? -> thats not the real problem here. the problem is just that, e.g., you can have a 10^9 x 10 matrix easily in memory and you obtain a Q of shape 10^9 x 10 for mode="reduced", but a 10^9 x 10^9-shaped Q  for mode="complete". in short: for "complete", the size in memory of the QR can be an arbitrarily large multiple of the size of the original data, depending on the shape of the matrix

2024-04-17 11:01 UTC, mrfh92 commented on heat/core/linalg/qr.py
I tried to clarify this.

2024-04-17 11:02 UTC, mrfh92 commented on heat/core/linalg/qr.py
> +        Higher choices may result in higher memory consumption. 0 corresponds to merging all processes at once.
I think its not possible to explain this in sufficient detail in the docs, but I added a warning that only users familiar with the algorithm should play around with this parameter.

2024-04-17 11:26 UTC, mrfh92 commented
I have addressed all except for the last comment; the last one I didnt understand because I dont see the inconsistency that is not there (?).

2024-04-17 13:52 UTC, ClaudiaComito approved these changes
Awesome @mrfh92 thank you so much!

2024-04-17 17:40 UTC, merged