Features/1456 add tall skinny svd
helmholtz-analytics/heat pull request #1468
Opened 2024-05-03 07:58 UTC by mrfh92

## Due Diligence

- General:
    - [ ]  **title** of the PR is suitable to appear in the [Release Notes](https://github.com/helmholtz-analytics/heat/releases/latest)
- Implementation:
    - [ ] unit tests: all split configurations tested
    - [ ] unit tests: multiple dtypes tested
    - [ ] documentation updated where needed

## Description

Issue/s resolved: #

## Changes proposed:

-
-
-
-

## Type of change

## Memory requirements

## Performance

#### Does this change modify the behaviour of other functions? If so, which?
yes / no

2024-06-10 09:20 UTC, ClaudiaComito requested changes
Looks good to me @mrfh92 , just a few minor changes (see below).  

Does it make sense to add a benchmarking function for SVD already? 

Also, did you want to add a PR description?

Thanks again!

2024-06-17 15:52 UTC, mrfh92 commented on heat/core/linalg/svd.py
> +                    Utilde_loc.shape,
taken into account

2024-06-19 08:38 UTC, ClaudiaComito approved these changes
Great, thanks a lot @mrfh92 !

2024-06-20 14:18 UTC, mrfh92 commented
@ClaudiaComito I have re-requested review to let the CI matrix run again after merging main.

2024-06-20 18:47 UTC, ClaudiaComito approved these changes

2024-06-20 19:58 UTC, merged