Features/1457 Add randomized SVD
helmholtz-analytics/heat pull request #1561
Opened 2024-07-08 11:47 UTC by mrfh92

## Due Diligence

- General:
    - [ ]  **title** of the PR is suitable to appear in the [Release Notes](https://github.com/helmholtz-analytics/heat/releases/latest)
- Implementation:
    - [ ] unit tests: all split configurations tested
    - [ ] unit tests: multiple dtypes tested
    - [ ] documentation updated where needed

## Description

Issue/s resolved: #

## Changes proposed:

-
-
-
-

## Type of change

## Memory requirements

## Performance

#### Does this change modify the behaviour of other functions? If so, which?
yes / no

2024-09-06 11:28 UTC, mrfh92 commented on heat/core/random.py
> +    #    raise ValueError(f"Shape is to big with {total_elements} elements")
actually this needs to be kept, but without being commented out

2024-09-06 11:36 UTC, mrfh92 commented on heat/decomposition/pca.py
> +        iterated_power: Union[str, int] = 0,
done

2024-09-06 11:36 UTC, mrfh92 commented on heat/decomposition/pca.py
> +        iterated_power: Union[str, int] = 0,
docs for PCA are now complete

2024-09-09 03:44 UTC, ClaudiaComito requested changes
Looks great, only a couple tiny changes needed as far as I'm concerned. Thanks @mrfh92 !

2024-09-09 07:18 UTC, mrfh92 commented on heat/core/random.py
> +    #    raise ValueError(f"Shape is to big with {total_elements} elements")
has been resolved meanwhile

2024-09-09 07:28 UTC, mrfh92 commented on heat/core/linalg/svdtools.py
> +    if not A.dtype == types.float32 and not A.dtype == types.float64:
I have introduced `heat_type_is_realfloating` (as there already existed `heat_type_is_complexfloating`)

2024-10-01 14:03 UTC, ClaudiaComito commented on heat/core/linalg/svdtools.py
> +    if not A.dtype == types.float32 and not A.dtype == types.float64:
@mrfh92 did you push the modified `types` module?

2024-10-01 15:10 UTC, ClaudiaComito requested changes
Thanks for addressing all the comments, I found a few typos, otherwise this looks great.

2024-10-01 15:10 UTC, ClaudiaComito commented on heat/core/linalg/svdtools.py
> +        number of processes to merge at each step of QR decomposition in the power iteration (if power_iter > 0). The default is 2. See the corresponding remarks for `heat.linalg.qr` for more details
```suggestion
        number of processes to merge at each step of QR decomposition in the power iteration (if power_iter > 0). The default is 2. See the corresponding remarks for :func:`heat.linalg.qr() <heat.core.linalg.qr.qr()>` for more details.
```

Not 100% sure but I think this is the way to render links to other functions on ReadTheDocs.

2024-10-04 14:10 UTC, mrfh92 commented
@ClaudiaComito thanks for reading so carefully that you found all the typos I had overlooked :+1:

2024-10-14 07:34 UTC, ClaudiaComito approved these changes
Great, thanks @mrfh92 !

2024-10-18 07:06 UTC, ClaudiaComito approved these changes

2024-10-18 07:16 UTC, merged