Features/178 tile
helmholtz-analytics/heat pull request #673
Opened 2020-09-17 13:45 UTC by ClaudiaComito

## Description

Implementation of heat version of np.tile():
https://numpy.org/doc/stable/reference/generated/numpy.tile.html

- process-local operations via torch.repeat()
- distributed tiling via blocking communication when repeats occur along the split axis. 
- also, introducing sanitation module #468 (with only a few basic functions), the idea is to expand it on the fly as needed

Issue/s resolved: #178 

## Changes proposed:
- Implemented new function: `manipulations.tile()`
- Initiated new module: sanitation, with functions `sanitize_input()`, `sanitize_sequence()`, `scalar_to_1d()`
- Implemented tests.

## Type of change

## Due Diligence

- [x] All split configurations tested
- [x] Multiple dtypes tested in relevant functions
- [x] Documentation updated (if needed)
- [ ] Updated changelog.md under the title "Pending Additions"

#### Does this change modify the behaviour of other functions? If so, which?
no

2020-12-08 14:49 UTC, mtar commented
Is the change of the split axis intended?

```python
>>> ht.tile(ht.array([1,2,3],split=0), [1,1])
DNDarray([[1, 2, 3]], dtype=ht.int64, device=cpu:0, split=1)
```

2021-07-09 12:02 UTC, ClaudiaComito commented
> Is the change of the split axis intended?
> 
> ```python
> >>> ht.tile(ht.array([1,2,3],split=0), [1,1])
> DNDarray([[1, 2, 3]], dtype=ht.int64, device=cpu:0, split=1)
> ```

@mtar belated thanks for commenting, yes you are tiling a 1-D array with  2-dimensional repetitions, in this case `tile()` will prepend the missing dimension (just like `numpy.tile()`, so the split axis nominally increases by one in this case.

2021-07-13 08:45 UTC, coquelin77 commented
rerun tests

2021-07-13 09:16 UTC, coquelin77 commented on heat/core/manipulations.py
> +    else:
very very minor comment: since you have a return in the line above, you dont need an else block here at all

2021-07-13 09:36 UTC, coquelin77 requested changes
the code itself looks fine, but i found a bug in the alltoallv logic:

```python
x = ht.arange(3*3).reshape((3, 3)).resplit(1)
print(x)
>>> DNDarray([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]], dtype=ht.int32, device=cpu:0, split=1)
y = ht.tile(x, (2, 3))
print(y)
>>> DNDarray([[        0,         4,         2,         0,         4,         2,         0,         4,         2],
              [        1,         1,         0,         1,     22065,     32628,         1,     32628,         0],
              [        3,         0,         0,         3,         0, 724118576,         3,         0,         0],
              [        0,         4,         2,         0,         4,         2,         0,         4,         2],
              [        1,         1,         0,         1,     22065,     32628,         1,     32628,         0],
              [        3,         0,         0,         3,         0, 724118576,         3,         0,         0]], dtype=ht.int32, device=cpu:0, split=1)
```

2021-08-20 14:47 UTC, coquelin77 commented
> > the code itself looks fine, but i found a bug in the alltoallv logic:
> > ```python
> > x = ht.arange(3*3).reshape((3, 3)).resplit(1)
> > print(x)
> > >>> DNDarray([[0, 1, 2],
> >               [3, 4, 5],
> >               [6, 7, 8]], dtype=ht.int32, device=cpu:0, split=1)
> > y = ht.tile(x, (2, 3))
> > print(y)
> > >>> DNDarray([[        0,         4,         2,         0,         4,         2,         0,         4,         2],
> >               [        1,         1,         0,         1,     22065,     32628,         1,     32628,         0],
> >               [        3,         0,         0,         3,         0, 724118576,         3,         0,         0],
> >               [        0,         4,         2,         0,         4,         2,         0,         4,         2],
> >               [        1,         1,         0,         1,     22065,     32628,         1,     32628,         0],
> >               [        3,         0,         0,         3,         0, 724118576,         3,         0,         0]], dtype=ht.int32, device=cpu:0, split=1)
> > ```
> 
> Good catch! Fixed

then this is ready as far as i can tell

2021-08-20 14:48 UTC, coquelin77 approved these changes

2021-08-20 14:52 UTC, merged