Enhancement/jenkins
helmholtz-analytics/heat pull request #717
Opened 2021-01-25 14:24 UTC by mtar

## Description

A CI solution in Jenkins

## Due Diligence
- [ ] Updated changelog.md under the title "Pending Additions"

#### Does this change modify the behaviour of other functions? If so, which?
no

2021-01-25 15:52 UTC, mtar commented
rerun tests

2021-02-01 13:37 UTC, bhagemeier requested changes
I think the changes of this PR deserve being mentioned in CHANGELOG.md. Even a change of the CI infrastructure, which is transparent to most users, should not be neglegted entirely.

2021-02-01 14:18 UTC, bhagemeier approved these changes

2021-02-01 14:19 UTC, bhagemeier commented
This PR should not change the code coverage at all. Therefore, I am in favor of ignoring this particular failing check.

2021-02-01 15:15 UTC, merged