Features/746 print0 print toggle
helmholtz-analytics/heat pull request #816
Opened 2021-06-22 12:43 UTC by coquelin77

## Description

Adds a toggle function to switch between local printing and global printing for easier usability and debugging.

Issue/s resolved: #746 

## Changes proposed:
- added local and global printing options
- added a print0 function to both the heat namespace and the builtins

## Type of change
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
  - this would only be a breaking change if another function relies on global printing and that is not set explicitly 

## Due Diligence

- [x] All split configurations tested
- [x] Multiple dtypes tested in relevant functions
- [x] Documentation updated (if needed)
- [x] Updated changelog.md under the title "Pending Additions"

#### Does this change modify the behaviour of other functions? If so, which?
yes -> the built in print statement will change depending on which mode is selected

2021-06-22 12:48 UTC, coquelin77 commented
this might fail on coverage but im not sure how to test `print0`. any ideas for how to test this @Markus-Goetz ?

2021-07-13 08:44 UTC, coquelin77 commented
rerun tests

2021-07-28 09:38 UTC, mtar requested changes
What do you think about printing the local metadata too? Similar to DNDarray. `LNDarray([], dtype, device, split)` or something like that. It can be useful for debugging.

2021-07-28 09:38 UTC, mtar commented on heat/core/tests/test_printing.py
> +        ht.global_printing()
put in setUp() and delete in all tests

2022-01-11 14:46 UTC, mtar approved these changes

2022-01-24 14:55 UTC, merged