add swapaxes
helmholtz-analytics/heat pull request #853
Opened 2021-07-30 07:43 UTC by mtar

## Description

Adds swapaxes. It is mostly an alias function for transpose on two axes.

Issue/s resolved: #849 

## Changes proposed:
- add swapaxes

## Type of change

## Due Diligence

- [x] All split configurations tested
- [x] Multiple dtypes tested in relevant functions
- [x] Documentation updated (if needed)
- [x] Updated changelog.md under the title "Pending Additions"

#### Does this change modify the behaviour of other functions? If so, which?
no

skip ci

2021-07-30 07:58 UTC, mtar commented
run tests

2021-08-18 10:00 UTC, ClaudiaComito requested changes
Great @mtar! Just a couple small things (removal of instance checks and implementation of method)

2021-08-20 12:10 UTC, mtar commented on heat/core/tests/test_manipulations.py
> +from typing import Type
No

2021-08-20 12:10 UTC, mtar commented on heat/core/manipulations.py
> +
nice catch

2021-08-20 12:12 UTC, mtar commented on heat/core/manipulations.py
> +    axes[axis1], axes[axis2] = axes[axis2], axes[axis1]
changed

2021-08-20 13:00 UTC, coquelin77 submitted a review, later dismissed
same as #854 looks good with changes already addressed. merging

2021-08-20 13:07 UTC, merged