Feature/337 determinant
helmholtz-analytics/heat pull request #877
Opened 2021-10-04 10:37 UTC by mtar

## Description

First implementation of determinant computation using Gaussian elimination with partial pivoting.

Issue/s resolved: #337 

## Changes proposed:
- add linalg.det

## Type of change

- New feature

## Due Diligence

- [ ] All split configurations tested
- [ ] Multiple dtypes tested in relevant functions
- [ ] Documentation updated (if needed)
- [ ] Updated changelog.md under the title "Pending Additions"

#### Does this change modify the behaviour of other functions? If so, which?
no

2021-11-09 09:50 UTC, coquelin77 requested changes
looks great to me. Just a small change

2021-11-09 09:50 UTC, coquelin77 commented on heat/core/linalg/basics.py
> +    if a.split is None or a.split < a.ndim - 2:
```suggestion
    if not a.is_distributed() or a.split < a.ndim - 2:
```
might need to change the error messages to be consistent

2022-01-04 11:00 UTC, coquelin77 commented
@mtar i have changed the shape rules to line up with torch's results. can you check this again?

2022-01-12 14:18 UTC, mtar commented
@coquelin77 Thanks for addressing the wrong dimension of the result tensor.

I was now able to reduce some lines of code due to a fix in master.

2022-01-12 15:47 UTC, mtar commented on heat/core/linalg/basics.py
> +        raise RuntimeError("DNDarray must be at least two-dimensional.")
I'm not sure if we should follow the error types of PyTorch. It's RuntimeError mostly.

2022-01-24 07:22 UTC, coquelin77 approved these changes

2022-01-24 07:22 UTC, merged