Feature/886 cholesky
helmholtz-analytics/heat pull request #893
Opened 2021-12-07 11:20 UTC by mtar

## Description

A first idea of the cholesky decomposition. Checks and Tests are missing

Issue/s resolved: #886

## Changes proposed:
- cholesky decomposition

## Type of change

## Memory requirements

## Performance

## Due Diligence
- [ ] All split configurations tested
- [ ] Multiple dtypes tested in relevant functions
- [ ] Documentation updated (if needed)
- [ ] Updated changelog.md under the title "Pending Additions"

#### Does this change modify the behaviour of other functions? If so, which?
yes, _binary_op

skip ci

2022-02-04 11:07 UTC, mtar commented
run test

2022-02-04 11:07 UTC, mtar commented
run tests

2022-02-04 16:33 UTC, mtar commented
rerun tests

2022-02-04 16:37 UTC, mtar commented
rerun tests

2022-02-07 08:05 UTC, mtar commented
run tests

2022-02-07 08:10 UTC, mtar commented
run tests

2022-02-07 09:42 UTC, mtar commented
rerun tests

2022-02-07 09:49 UTC, mtar commented
run tests

2022-02-14 08:54 UTC, coquelin77 commented on CHANGELOG.md
> +- [#875](https://github.com/helmholtz-analytics/heat/pull/875) New feature `inv
```suggestion
- [#875](https://github.com/helmholtz-analytics/heat/pull/875) New feature `inv`
```

2022-02-14 08:54 UTC, coquelin77 commented on heat/core/linalg/basics.py
> +    Returns the Cholesky decomposition of a Hermitian or symmetric positive-definite matrix.
add a note saying this doesnt work for complex values (also change the examples)

2022-04-22 07:51 UTC, mtar commented
run tests

2022-04-25 11:15 UTC, mtar commented
run tests

2022-04-25 11:33 UTC, mtar commented
Can't increase coverage, missing lines require pytorch 1.8/1.9

2022-07-04 04:39 UTC, ClaudiaComito requested changes
Thanks a lot for addressing this @mtar, and sorry for taking so long to review. 

I think we need to address the complex datatype issue and the need for gathering data before merging this.  Let's discuss during today's PR talk.

2022-07-04 04:39 UTC, ClaudiaComito commented on heat/core/linalg/basics.py
> +    Returns the Cholesky decomposition of a Hermitian or symmetric positive-definite matrix.
Inconsistent documentation (decomposition of a Hermitian doesn't work on complex data types)

2022-07-04 04:39 UTC, ClaudiaComito commented on heat/core/linalg/basics.py
> +        Whether a lower or upper triangular matrix is returned.
"whether an upper triangular ... is returned"

2022-07-04 04:39 UTC, ClaudiaComito commented on heat/core/linalg/basics.py
> +    """
Inconsistent docs

2022-07-04 04:39 UTC, ClaudiaComito commented on heat/core/linalg/basics.py
> +        raise RuntimeError("Last two dimensions of the DNDarray must be square.")
How about "Expected a DNDarray of shape (..., M, M), got ..." or "Last two dimensions of DNDarray must be equal, are ..."

2022-07-04 04:39 UTC, ClaudiaComito commented on heat/core/linalg/basics.py
> +        raise NotImplementedError("Not implemented for {}".format(x.dtype))
Why not cast DNDarray to corresponding float?

2022-07-04 04:39 UTC, ClaudiaComito commented on heat/core/linalg/basics.py
> +        )
We need to  diagnose the problem.

2022-07-04 04:39 UTC, ClaudiaComito commented on heat/core/linalg/basics.py
> +                )
I find it problematic that `b` needs to be gathered. This is basically an outer product, isn't it? Distributed `outer` is implemented, and we should be able to expand that functionality to a stack of vectors.

(Also it shouldn't be necessary to balance just before resplitting, if it is let's fix it)

2022-07-04 04:39 UTC, ClaudiaComito commented on heat/core/linalg/basics.py
> +                )
See above

2022-07-08 10:32 UTC, ClaudiaComito commented
@mtar as far as I can tell, `cholesky()` works perfectly on distributed positive-definite Hermitians as long as they are double precision.

Here's the code I'm running:

```python

# test CHOLESKY
a = ht.arange(100, dtype=ht.complex128, split=0)
a = ht.diag(a)
a[ht.where(a == 0)] = 1j
# a.resplit_(axis=1) # uncomment to test split along columns
b = a@a.conj().T # b is positive-definite Hermitian

np_b = b.numpy()

ht_cho = ht.linalg.cholesky(b)
np_cho = np.linalg.cholesky(np_b)
t_cho =  torch.linalg.cholesky(torch.tensor(np_b))

print("ht == np ?", np.allclose(ht_cho.numpy(), np_cho))
print("ht == t ?", torch.allclose(torch.tensor(ht_cho.numpy()), t_cho))
```

2023-02-14 16:51 UTC, mrfh92 reviewed
**Review of "Feature/886-cholesky"**
The code under review adds Cholesky decomposition to the linalg-module of Heat. For two-dimensional inputs, Cholesky decomposition is computed utilizing a serial algorithm; for three- or more-dimensional inputs the decomposition is computed in batch-wise manor applying `torch.linalg.cholesky` to the last two dimensions of the input. Complex inputs are excluded so far.  

- I do not know applications in which we would have to deal with complex data. Therefore, from my point of view it does not make problems if we exclude (at least for the moment) complex data types for Cholesky although they are possible in general 
- Just a comment: I like the distinction between `dim = 2` and `dim > 2` very much. I guess, we should add this type of “batch-linear-algebra” for `dim > 2` for other routines as well.  
- The code for `dim=2` look very “serial”. Indeed, a scaling test on up to 24 processes (2 threads each) on 2 nodes of HDFML yields rather unexpected scaling behavior (which may also be due to the small size of the test matrices…).
- As far as I see, there is no error message for the case that the matrix turns out not to be positive definite. Moreover, it is not checked whether the matrix is symmetric. Since the code targets non-expert-users this may be useful, even if expensive. 

All in all, I suggest that we decide in the PR meeting together whether this PR should be merged as it is (in order to add the functionality) or whether we want to wait for a distributed implementation of Cholesky (for `dim >2`) possibly originating from GSoC. 

![cpu](https://user-images.githubusercontent.com/112093564/218803265-ccedce88-b04a-493a-bd0e-b7586ebbc4e6.jpg)

2023-04-17 15:13 UTC, mrfh92 commented
Closed due to decision in second-last PR talk.

2023-04-17 15:13 UTC, closed without merging