fix size bug in randint
helmholtz-analytics/heat pull request #916
Opened 2022-02-08 11:54 UTC by mtar

## Description

Issue/s resolved: #913 

## Changes proposed:
- allow ints for size in randint

## Type of change

- Bug fix

## Memory requirements

n/a

## Performance

n/a

## Due Diligence
- [x] All split configurations tested
- [x] Multiple dtypes tested in relevant functions
- [x] Documentation updated (if needed)
- [x] Updated changelog.md under the title "Pending Additions"

#### Does this change modify the behaviour of other functions? If so, which?
no

2022-02-09 05:24 UTC, ClaudiaComito requested changes
Thanks a lot @mtar for looking into this right away! I found another inconsistency vs. numpy, see comments.

2022-02-09 05:24 UTC, ClaudiaComito commented on heat/core/random.py
I was thinking of addressing this like we do for `shape` in `ht.reshape()`:
´´´python
def reshape(a: DNDarray, *shape: Union[int, Tuple[int, ...]], **kwargs) -> DNDarray:
   ...
´´´

Default `size` should be `0`, not `None`. Here a numpy example:
```bash
>>> d = np.random.randint(0,50)
>>> d
1
>>> d = np.random.randint(0,50, 1)
>>> d
array([0])
>>> e = ht.random.randint(0,50)
>>> e
DNDarray([9], dtype=ht.int32, device=cpu:0, split=None)  # ndim=1 but should be 0!
```

2022-02-09 05:24 UTC, ClaudiaComito commented on heat/core/tests/test_random.py
> +
Add tests where no size is specified and scalar is returned?

2022-02-09 09:06 UTC, mtar commented
rerun tests

2022-02-14 15:07 UTC, mtar commented
reru tests

2022-02-14 15:08 UTC, mtar commented
run tests

2022-02-14 17:07 UTC, merged