Implement isin()
helmholtz-analytics/heat pull request #962
Opened 2022-04-12 07:14 UTC by Dhruv454000

## Description

Implement isin() functionality in heat.

Issue/s resolved: #450

## Type of change

- New feature 

## Due Diligence
- [ ] All split configurations tested
- [ ] Multiple dtypes tested in relevant functions
- [ ] Documentation updated (if needed)
- [ ] Updated changelog.md under the title "Pending Additions"

#### Does this change modify the behaviour of other functions? If so, which?
 no

2022-04-12 07:14 UTC, mtar commented
GPU cluster tests are currently disabled on this Pull Request.

2023-08-21 10:39 UTC, mrfh92 commented
see #450 - this PR, however, is as far as I see only concerned with `in1d` only. 
Can serve as a starting point to implement `isin()` also. 

(Reviewed within #1109 )

2023-10-16 03:44 UTC, ClaudiaComito requested changes
@Dhruv454000 I hope you're well. I have to apologize, this PR got buried somehow. If you're still interested and have time, I can help you finish it. 

If we don't hear from you within two weeks, I'll finish the PR. Thanks again for your time!

2023-10-16 03:44 UTC, ClaudiaComito commented on heat/core/logical.py
> +    "in1d",
this list should be in alphabetical order

2023-10-16 03:44 UTC, ClaudiaComito commented on heat/core/logical.py
> +    y : DNDarray or scalar
We should implement `isin`, and then alias `in1d` to a special case of `isin`.

We can use the generic  `_operations.binary_op` function with `torch.isin` as local function, there's no need to implement the algorithm from scratch.

2024-08-05 02:24 UTC, closed without merging